
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: instana-exporter
  labels:
    app: instana-exporter
spec:
  serviceName: instana-exporter
  selector:
    matchLabels:
      app: instana-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: instana-exporter
    spec:
      containers:
        - name: instana-exporter
          image: "image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/zapm-instana-exporter:6.1.0-16" #input01
          imagePullPolicy: IfNotPresent
# Uncomment section below if using TLS in communicating with the Instana server,
# and an internally signed CA or a self-signed certificate is used on the server.
#          volumeMounts:
#            - mountPath: "/var/certs"
#              name: input24
#              readOnly: true
          env:
            - name: ZAPM_KAFKA_SERVER
              value: "kafka-internal-svc:9092"
            - name: ZAPM_LOG_LEVEL
              value: "INFO"
            - name: ZAPM_INSTANA_HOST
              value: "https://serverless-orange-saas.instana.io" # input21
            - name: ZAPM_INSTANA_AGENT_KEY
              value: "AGENT-KEY-SECRET" # input22
            - name: ZAPM_INSTANA_IS_SAAS
              value: "true" # input23
            # - name: ZAPM_INSTANA_PROXY_HOST
            #   value: "input26"
            # - name: ZAPM_INSTANA_PROXY_PORT
            #   value: "input27"
# Uncomment section below if using TLS in communicating with the Instana server,
# and an internally signed CA or a self-signed certificate is used on the server.
#            - name: ZAPM_INSTANA_USE_CERT
#              value: "true"
#            - name: ZAPM_INSTANA_CERT_NAME
#              value: input25
#      volumes:
#        - name: input24
#          secret:
#            secretName: input24
